### ISSUE TITLE
クリーンアップリソース追加

### ISSUE THREAD

**Issue by FV-d-yagi** [jaws-ug-kanazawa/Runbook#10]
「ルールエンジンの作成」で作った以下　２つの削除は不要でしょうか？
- 手順書では[20220619s3rule]
- 手順書では[IAM Role 20220619IoT]

**Comment by otanikohei** [comment]
サブスクリプション
[data/20220619things] も残っていました。

**Comment by matyuda** [comment]
@otanikohei 
以下はお気に入りに入れた場合に残っている認識でいますが、異なっていましたらご指摘ください。
> サブスクリプション
> [data/20220619things] も残っていました。
