### ISSUE TITLE
証明書の手順

### ISSUE THREAD

**Issue by shigeru-oda** [jaws-ug-kanazawa/Runbook#4]
正解が分かってないので、issuesで。

証明書関係は３つ作成されます。
- xxx-certificate
- xxx-private.pem.key
- xxx-public.pem.key

その後にUpされるファイルは
- xxx-private.pem.key
- xxx-public.pem.key
であり、private.pem.keyはprivate.pemにリネームされます

結果、以下２ファイルが設定される認識です。
- private.pem
- xxx-public.pem.key

しかし、その後のPythonを実行すると
```
FileNotFoundError: [Errno 2] No such file or directory: 'certificate.crt'
```
とエラー出力されるのでxxx-certificateもUpLoad必要では？と思っていますが認識あっていますか？

**Comment by matyuda** [comment]
xxx-certificate
xxx-private.pem.key
の2つが使われます。

公開鍵はダウンロードしますが、不要です。
手順書に追記しておきます。

**Comment by matyuda** [comment]
https://github.com/jaws-ug-kanazawa/Runbook/blob/main/books/aws-iot-handson-doc/3-setup-iot-client.md?plain=1#L59
へ反映しました。
