### ISSUE TITLE
AWS IoT画面でのテスト

### ISSUE THREAD

**Issue by shigeru-oda** [jaws-ug-kanazawa/Runbook#7]
スクショを取られている場所がどの画面かが分からず、場所を記載いただけますでしょうか。

**Comment by otanikohei** [comment]
僕もテスト画面が見つけられませんでした。
テスト > MQTT テストクライアント でしょうか。サブスクリプションには何もありません。

**Comment by otanikohei** [comment]
サブスクライブしたら上手く行きました。

![スクリーンショット 2022-06-12 20 32 22](https://user-images.githubusercontent.com/71739020/173231095-5b36cf64-c666-4d1d-bc57-4274a1d195e6.png)
