### ISSUE TITLE
誤字脱字など

### ISSUE THREAD

**Issue by otanikohei** [jaws-ug-kanazawa/Runbook#8]
1. 適当な名前を入力し、その他の設定は行わず、画面下の次へを押します
 モノの名前はエンドポイントと同様、控えておくよう案内文を記載すると丁寧かと思いました。
2. ディバイス証明書、キーファイルをダウンロードして完了のボタンを押します。
 コンソールの表記と同じ、ディバイス → デバイス がよろしいかと感じました。
 また、証明書はこのタイミングしかダウンロードできないので閉じる前にダウンロードするよう案内文を記載すると丁寧かと思いました。
3. 以下のように置換し保存を押します。
 シャドウの状態を編集する箇所は、保存ではなく、更新ボタンでした。
4. ルールアクションを設定する箇所で、キーが必須でした。
5. Issue #7 と重複しますが、テストのサブスクライブを設定する手順が必要でした。

**Comment by matyuda** [comment]
ご指摘ありがとうございます。
キーの設定については、「test」を入力する手順の記載がありますが、必須であることを明示した方が良さそうでしょうか？

**Comment by matyuda** [comment]
修正完了しました。
